import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    AZURE_FORM_RECOGNIZER_ENDPOINT = os.getenv("AZURE_FORM_RECOGNIZER_ENDPOINT")
    AZURE_FORM_RECOGNIZER_KEY = os.getenv("AZURE_FORM_RECOGNIZER_KEY")
    AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
    AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")
    AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
    AZURE_OPENAI_MODEL = os.getenv("AZURE_OPENAI_MODEL")
    AZURE_OPENAI_API_TYPE = os.getenv("AZURE_OPENAI_API_TYPE")
    AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")

    GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
    EMAIL_VERIFIER_API = os.getenv("EMAIL_VERIFIER_API")
    TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
    TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")

    AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
    AZURE_CONTAINER_NAME_FOR_ORGANIZED_DATA = os.getenv("AZURE_CONTAINER_NAME_FOR_ORGANIZED_DATA")
    AZURE_CONTAINER_NAME_FOR_BLOB = os.getenv("AZURE_CONTAINER_NAME_FOR_BLOB")
    AZURE_CONTAINER_NAME_FOR_EXTRACTED_EMAILS=os.getenv("AZURE_CONTAINER_NAME_FOR_EXTRACTED_EMAILS")
    AZURE_CONTAINER_NAME_FOR_EXTRACTED_TEXT_FILE = os.getenv("AZURE_CONTAINER_NAME_FOR_EXTRACTED_TEXT_FILE")
    AZURE_STORAGE_ACCOUNT_NAME=os.getenv("AZURE_STORAGE_ACCOUNT_NAME")
    AZURE_STORAGE_ACCOUNT_KEY=os.getenv("AZURE_STORAGE_ACCOUNT_KEY")
    AZURE_SIGNALR_CONNECTIONSTRING=os.getenv("AZURE_SIGNALR_CONNECTIONSTRING")